name: run-tests
on: [push]
jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
        - name: checkout files
          uses: actions/checkout@v2
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Install dependencies
          run: | 
              python -m pip install --upgrade pip
              pip install pytest pytest-cov
        - name: Run tests
          run: python -m pytest tests/
        - name: Code Coverage
          run: python -m pytest --cov=power tests/
